version: '3'
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      codeigniter_net:
    ports:
      - "8181:90"
    restart: always

  php:
    image: copy-php
    volumes:
      - ./public:/public
    depends_on:
      - database
    networks:
      codeigniter_net:

  database:
    image: mysql:latest
    networks:
      codeigniter_net:
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST : database
      MYSQL_ROOT_PASSWORD : ci
      MYSQL_DATABASE : ci_app
      MYSQL_USER : php
      MYSQL_PASSWORD : php
    # env_file:
    #   - .env

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8282:80'
    environment:
      MYSQL_HOST : database
      MYSQL_ROOT_PASSWORD : ci
      MYSQL_DATABASE : ci_app
      MYSQL_USER : php
      MYSQL_PASSWORD : php
      PMA_HOST : database
      PMA_PORT : 3306

    networks:
      codeigniter_net:

networks:
  codeigniter_net:

